ToonYou:
  base: ""
  path: "models/DreamBooth_LoRA/toonyou_beta3.safetensors"
  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"

  seed:           [10788741199826055526, 6520604954829636163, 6519455744612555650, 16372571278361863751]
  steps:          25
  guidance_scale: 7.5

  prompt:
    - "a small house in the middle of a forest, a detailed matte painting inspired by Vassily Maximov, cgsociety, photorealism, soft focus matte painting, photorealistic matte painting, 3d rendered matte painting"
    

  n_prompt:
    # - ""
    - "(embedding:FastNegativeV2:1.1), (embedding:ng_deepnegative_v1_75t:1.1), (embedding:badhandv4:1.1), wrinkles, deformed, unrealistic, worst quality, blurry, fuzzy, out of focus, low quality, out of frame, logo, signature, username, watermark, picture frame, frames, borderline, duplicate, error, ugly, blur, tiled, extra fingers, deformed hands, polydactyl:1.5"
    # - ""
    # - ""
